### ISSUE TITLE
Exception building Arm32Hfp from Ubuntu x64

### ISSUE THREAD

**Issue by parkkun0** [danbrough/kotlinxtras#2] opened 2022-09-28 11:25 UTC
Hi I've been doing this PoC if a library in a KMP common that uses Ktor could work on Arm32 RPI.

I am using x64 Ubuntu 20.04 to build my project.

I am getting this gradle failure which seems to be a issue on a linker.

```
e: /home-mc/kaiser.park/.konan/dependencies/arm-unknown-linux-gnueabihf-gcc-8.3.0-glibc-2.19-kernel-4.9-2/arm-unknown-linux-gnueabihf/bin/ld invocation reported errors

The /home/spark/.konan/dependencies/arm-unknown-linux-gnueabihf-gcc-8.3.0-glibc-2.19-kernel-4.9-2/arm-unknown-linux-gnueabihf/bin/ld command returned non-zero exit code: 1.
output:
/home/spark/.konan/dependencies/arm-unknown-linux-gnueabihf-gcc-8.3.0-glibc-2.19-kernel-4.9-2/arm-unknown-linux-gnueabihf/bin/ld.bfd: cannot find -lssl
/home/spark/.konan/dependencies/arm-unknown-linux-gnueabihf-gcc-8.3.0-glibc-2.19-kernel-4.9-2/arm-unknown-linux-gnueabihf/bin/ld.bfd: cannot find -lcrypto
/home/spark/.konan/dependencies/arm-unknown-linux-gnueabihf-gcc-8.3.0-glibc-2.19-kernel-4.9-2/arm-unknown-linux-gnueabihf/bin/ld.bfd: cannot find -lcurl
```

This error started to appear when I swapped to following packages.
```
//mavenCentral()
implementation("org.danbrough.ktor:ktor-client-core:$ktorVersion")
implementation("org.danbrough.ktor:ktor-client-content-negotiation:$ktorVersion")
implementation("org.danbrough.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
```

I've been trying to see what could have caused a problem, but the Ktor submodule in the repo directory does not have a link (ktor @ 1e82c30).

* If you don't mind, can you share ktor repository public, so I can grasp what you have changed on ktor project to make Arm32 work?
* Does your mavenCentral dependencies also require ssl, curl, crypto to be located in `/usr/local/kotlinxtras/libs/` as well?

**Comment by parkkun0** [comment] 2022-09-28 11:44
Wuw. I'm sorry. I just saw your repositories again, and I found it is there. please forget my first question. My bad.

**Comment by danbrough** [comment] 2022-09-28 18:50
Yup. The openssl and curl target libraries are required to be in specific positions for the ktor support.
Either at /usr/local/kotlinxtras/libs/[openssl,curl]/linuxArm32Hfp/lib  or in ./build/kotlinxtras/[openssl,curl]/linuxArm32Hfp/lib.
The demos/ktor uses the first and demos/ktor_standalone will use the latter.
I am working on a gradle plugin that will download and unpack prebuilt libraries into your build/kotlinxtra/ folder.
That's not working at the moment.
I'll merge it into the 0.0.1-beta04 release and merge it into the main branch.
I'll let you know when that's done.

**Comment by parkkun0** [comment] 2022-09-29 08:04
Thanks! Look forward to it

**Comment by parkkun0** [comment] 2022-10-05 08:58
Do you ever get errors related to `iconv` references?

I get `Uncaught Kotlin exception: kotlin.IllegalArgumentException: Failed to open iconv for charset ISO-8859-1 with error code 22` from `CharsetNative.kt` in Ktor project.

I thought Ktor would eventually call iconv in `/usr/lib`, so I've cross-compiled libiconv from GNU and installed it on my Arm32 RPi but still getting the error.

I am basically wondering if I need to manually link `iconv.so` and `.h` to a Ktor project you tweaked. Maybe using C Interops or something.

I know you know much broader insight with regards to Kotlin Multiplatform projects and how to build them. I was hoping if you can guide me where I can kind of start to tackle.

Thanks in advance,

**Comment by danbrough** [comment] 2022-10-07 01:05
LD_LIBRARY_PATH set to the libraries on your RPI ?
I haven't found a need for them but I haven't used ktor much.

**Comment by parkkun0** [comment] 2022-10-08 15:54
Yes, the path is set correctly. There is still a chance that I might have cross compiled with wrong prefixes and stuff.

I will try the C interop option then.

Thanks for the answer though.

**Comment by danbrough** [comment] 2022-10-11 07:20
Not sure.
I'm not far away from releasing a 0.0.1-beta04 with ktor 2.1.2 and
precompiled binaries to link against.
The demo isn't working yet but once it is perhaps you could modify
demos/ktor_standalone to reproduce the error
so I can have a look at it.
cheers,
Dan

**Comment by parkkun0** [comment] 2022-10-17 09:47
After tedious debugging, I found out that it was due to missing encoding. `CharsetNative.kt` somehow uses UTF16 as a intermediate and my RPI was missing extra encodings required by `CharsetNative` (ISO-8859-1 and UTF-16). Since `platform.iconv.*` uses dynamically linked libc from the target system, I added missing encodings and it was all resolved.

Thanks to your project, it is working.

**Comment by danbrough** [comment] 2022-10-18 09:12
Oh. That's great news!  
I'm an ignorant monolingual person .. so you had to add  something to locale.gen?
Or did you have to provide a libiconv.so that was modified somehow?

I ran into issues with ktor and CharsetNative.kt while trying to compile android native versions.
platform.iconv is missing on android native. 
Perhaps many android implementations are based around older libc implementations that don't have iconv so they didn't provide it as a builtin api.
Because of that I've added iconv along with curl,openssl,sqlite to the dev branch but it's still a mess (still learning how gradle plugins work).
Off on holiday but will tidy it all up and check every demo works properly when I get back and merge it into the main branch.
Then I can get back to whatever it was I was working on that led me down this rabbit hole.
I've forgotten.. 
Glad that I've been of any help.

**Comment by parkkun0** [comment] 2022-10-19 06:37
```
I'm an ignorant monolingual person .. so you had to add something to locale.gen?
Or did you have to provide a libiconv.so that was modified somehow?

I ran into issues with ktor and CharsetNative.kt while trying to compile android native versions.
platform.iconv is missing on android native.
Perhaps many android implementations are based around older libc implementations that don't have iconv so they didn't provide it as a builtin api.
```
I think you have way more knowledge on computers and programming in general, so what I've done might not be a eligible solution lol.

I've lost the link but I found in google that if a program depends on libc gconv (iconv equivalent), which `platform.iconv` is, you can
1. Add so files for necessary encodings at /usr/lib/gconv directory
2. Adjust tables `gconv-modules`
3. run iconvconfig executable bin

Step 3 was not really necessary, but I did it anyway. I didn't know how to you locale.gen. 

I merely searched through konan compiler directory and found all those encodings and `iconvconfig` file in Arm32 compiler directory. I've simply copied them to the /usr/lib/gconv directory and ran iconvconfig as said earlier and it worked.

Hope this helps.

**Comment by danbrough** [comment] 2022-10-26 20:23
Thanks for that! 
That's been very helpful.

**Comment by danbrough** [comment] 2023-03-17 02:37
I'll close this but if you are still interested my ktor demo is working fine with the linux arm targets at:
https://github.com/danbrough/kotlinxtras/tree/main/demos/repos/ktor

**Closed as completed by danbrough** 2023-03-17 02:37 UTC
